import { Order } from "./Order";


export interface OrderItem {
  id?: number; // Optional because it will be generated by the server
  order: Order; // Reference to the associated Order
  itemName: string; // Name of the item
  quantity: number; // Quantity of the item
  price: number; // Price of a single item
  total: number; // Total price for this item (quantity * price)
}

